name: 'example'
description: 'Example project for the Automated Testing Framework.'
publish_to: 'none'
version: '1.0.0+10'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  automated_testing_framework_example: '^2.2.4+10'
  automated_testing_framework_plugin_gps: 
    path: '../'
  flutter: 
    sdk: 'flutter'
  flutter_map: '^2.1.1'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


flutter_icons: 
  android: true
  ios: true
  image_path: 'assets-src/icon.png'
  remove_alpha_ios: true

flutter_native_splash: 
  image: 'assets-src/splash.png'
  color: '212121'
  android_disable_fullscreen: true

flutter: 
  uses-material-design: true
  assets: 
    - 'assets/all_tests.json'
    - 'assets/tests/'
