name: 'automated_testing_framework_plugin_gps'
description: 'Library to use provide GPS related test steps to the Automated Testing Framework.'
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_plugin_gps'
version: '2.0.0+1'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  automated_testing_framework: '^4.0.1+1'
  convert: '^3.0.2'
  flutter: 
    sdk: 'flutter'
  form_validation: '^2.1.0+2'
  geolocator: '^8.2.1'
  json_class: '^2.1.2+4'
  logging: '^1.0.2'
  static_translations: '^2.1.1'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


flutter: 
  uses-material-design: true
