name: automated_testing_framework_plugin_gps
description: Library to use provide GPS related test steps to the Automated Testing Framework.
homepage: https://github.com/peiffer-innovations/automated_testing_framework_plugin_gps

version: 1.0.2+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  automated_testing_framework: ^3.2.3
  convert: ^3.0.1
  flutter:
    sdk: flutter
  form_validation: ^2.1.0+2
  geolocator: ^8.1.1
  json_class: ^2.1.2+4
  logging: ^1.0.2
  static_translations: ^2.1.0+2

# dependency_overrides:
#   automated_testing_framework:
#     path: ../automated_testing_framework
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
