name: automated_testing_framework_plugin_gps
description: Library to use provide GPS related test steps to the Automated Testing Framework.
homepage: https://github.com/peiffer-innovations/automated_testing_framework_plugin_gps

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  automated_testing_framework: ^3.1.0+2
  convert: ^3.0.0
  flutter:
    sdk: flutter
  form_validation: ^2.0.0
  geolocator: ^7.6.0
  json_class: ^2.0.0
  logging: ^1.0.1
  static_translations: ^2.0.1

# dependency_overrides:
#   automated_testing_framework:
#     path: ../automated_testing_framework
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
